### ISSUE TITLE
Issues with OpenFaaS labs

### ISSUE THREAD

**Issue by alexellis** [javajon/katacoda-courses#2]
Hi Jon,

I noticed some issues with the OpenFaaS labs on Katakoda and wondered if we could setup a brief call to walk through some of them and talk about your plans for the labs?

I also wanted to point you at these two resources which I think will help - https://docs.openfaas.com - https://www.openfaas.com/blog/five-cli-tips/

Here are a few initial comments. I realise you may not be finished with everything yet but hope this is useful for you?

* eval (minikube docker-env) didn't work and gave an error

```
$ eval $(minikube docker-env)
No command 'none' found, did you mean:
 Command 'note' from package 'note' (universe)
 Command 'node' from package 'nodejs-legacy' (universe)
 Command 'nona' from package 'hugin-tools' (universe)
 Command 'one' from package 'opennebula' (universe)
none: command not found
```

* The env-var $GW can be set to $OPENFAAS_URL then you don't have to specify `--gateway` - this is the convention - `export OPENFAAS_URL=$(minikube service gateway-external --namespace openfaas --url)`
* Patching the Prometheus service for a NodePort didn't work (we can suggest some better ways to do this)
* After doing faas-cli login you could do something like `faas-cli list` or `faas-cli store deploy`
* `faas-cli up` would be good to cover
* The local registry at localhost:5000 didn't seem to work for me
* We have instructions for generating a password in the docs - I would recommend using this over setting the password to "user"
* Add `-w` to this command to show when the resources become available `kubectl --namespace=openfaas get deployments -l "release=openfaas, app=openfaas"`
* Run `faas-cli version` - this is done by the CLI install script already could be skipped?
* In general the lab `Build, Deploy and Call a Python Function
Build` doesn't work. Why do `docker login` when you are using localhost:5000 for a registry?
* Under `Observability` you may be better using some of our workshop material (please give credit if you copy it) - we have an image for Grafana that can be used and has the dashboard pre-installed - https://github.com/openfaas/workshop/blob/master/lab2.md
* Might be nice to cover scaling or scaling from zero? https://github.com/openfaas/workshop/blob/master/lab9.md

Please also give a credit to where you got the installation setup commands (the OpenFaaS documentation/helm chart)

Thanks,

Alex

**Comment by javajon** [comment]
Hi Alex, 

Big thank you for your attention. All of these I absolutely agree with and perhaps we can add some other exemplary topics to showcase OpenFaaS. Beyond the incomplete steps, instructions, and bugs, the scaling from zero is perhaps the biggest todo. Working on posthaste. After the polishing let's discuss.

**Comment by javajon** [comment]
@alexellis - I polished up many things. With your helpful guidance as above. With the "up" command the Python function is available in a pod. However, I'm stuck on the Python invoke instruction in step 7. I even tried the simple example:
```
def handle(req):
    print("Hello! You said: " + req)
```
and when the function is invoked an error occurs. The pod log shows no problems and remains running. The function returns this error:  `<title>Error 502 (Server Error)!!1</title>`.  The same error can be consistently seen on the command line and in the portal.

If you could give it a quick try [here ](https://www.katacoda.com/javajon/courses/kubernetes-serverless/openfaas) you will probably see something I do not. To me, it's not clear yet what the problem could be.

Once I get unstuck the observability and scaling will be completed. I'm wide open to any other tips or messaging in the instructional text. 

Thank you for your time on this,

 - Jonathan

**Comment by ivanayov** [comment]
Hi John,

I tried to reproduce step 7, but did not have the 502 error. Seems like the gateway was not up when you tried or `$OPENFAAS_URL` was not set properly.

What I've noticed is that with: `cp fibonacci.py fibonacci/handler.py` you overwrite the handler file and don't have a handler method any more.

This gives an error
```
$ echo 5 | faas-cli invoke fibonacci
Server returned unexpected status code: 500 - exit status 1
Traceback (most recent call last):
  File "index.py", line 19, in <module>
    ret = handler.handle(st)
AttributeError: module 'function.handler' has no attribute 'handle'
```

You can try something like this instead:
```
cat << EOF > fibonacci/handler.py
def handle(req):
    # new code here
EOF
```

Best,

Ivana

**Comment by javajon** [comment]
@ivanayov Thank you for the feedback. This was the reality check to get me unstuck!  The old fibonacci.py code had a few problems. The scrollbar problem is out of my control as its controlled by Katacoda. If you could provide more clarity on what you experienced we can pass that to Ben Hall at Katacoda.  

@alexellis Your advice was also helpful. Retrospectively, my three frictions were:

1. Learn more Python and read the docs more ;-)
2. When Python fails this error message is the result. Being new, that was not clear. I will investigate the troubleshooting guide to see how I can reveal the Python failures.
3. I did not find in the documentation that the interface between OpenFaaS and the language (e.g. Python) is literally the "handle" method. This is implied in the documentation, the "new" templates, and all the examples, but not directly stated in the docs?  Perhaps a chart in the documentation could show the various language forms of "handle". Other serverless implementations have a differing signature with similar parameters. OpenFaaS has handle has a "req" parameter. What is its type?  Examples of more complex inputs and outputs for each language might illuminate that.  Perhaps it's already there in the docs, and forgive me if it is - recursive to point #1.  ;-)

**Comment by javajon** [comment]
Just wrapped up the last step for scaling. I think all the items suggested have been addressed. 

If you find anything else, just create an issue. Thank you both for your help.

**Comment by alexellis** [comment]
👍 please can you pop into Slack and advertise your course? I hope the community could try it out and give feedback. Thanks for working on the issue I raised.

**Comment by javajon** [comment]
@ivanayov **Thank you for the help.** There was a missing parenthesis ( ')' ) at the end of the source code. The Katacoda folks also just fixed a blocking issue on step 4. I just retested scenario and all steps are working again.

@alexellis Good idea. I'll post a message to Slack once registration completes.

**Comment by javajon** [comment]
@alexellis - Message posted:  

> News: A new way to learn OpenFaaS in a fast and disposable Kubernetes playground. There is a scenario on Katacoda.com and its free to use and share with other curious learners. The scenarios follow the similar steps found in the OpenFaaS labs. The advantage of Katacoda is it abstracts Kubernetes to allow you, the learner or teacher, to get right to the point. In a way, Katacoda embraces serverless. There are a growing number of scenarios on Katacoda to learn complex and interesting topics around containers, kubernetes, helm charts, languages, Linux.
> 
> I would love your feedback on the OpenFaaS tutorial, go and kick the tires:  https://www.katacoda.com/javajon/courses/kubernetes-serverless
