### ISSUE TITLE
License

### ISSUE THREAD

**Issue by FabioAntunes** [javajon/katacoda-courses#6]
Hey, @javajon thanks for putting these courses up. Would it be possible for you to add a license to the repo?

Thanks in advance

**Comment by javajon** [comment]
Hi Fábio,

Good idea. I just add Apache 2.0. What's your interest in the source? Can I
help?


   - *Jonathan Johnson*
   Software Architectures ★ Speaker ★ Workshop Hosting ★ Kubernetes & Java
   Specialist ★ Independent ★ Dijure, LLC <http://www.dijure.com>
