### ISSUE TITLE
tektonCLI installation error

### ISSUE THREAD

**Issue by suyogpatil** [javajon/katacoda-courses#7]
Getting issue in tektonCLI installation(step 5)
https://www.katacoda.com/javajon/courses/kubernetes-pipelines/tekton

Might be related to this https://askubuntu.com/questions/59458/error-message-sudo-unable-to-resolve-host-none

```
controlplane $ sudo apt update > /dev/null 2>&1 && \
> sudo apt install -y gnupg && \
> sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 3EFE0E0A2F2F60AA && \
> echo "deb http://ppa.launchpad.net/tektoncd/cli/ubuntu eoan main"|sudo tee /etc/apt/sources.list.d/tektoncd-ubuntu-cli.list && \
> sudo apt update > /dev/null 2>&1 && \> sudo apt install -y tektoncd-cli
sudo: unable to resolve host controlplane
Reading package lists... Done
Building dependency tree
Reading state information... Done
gnupg is already the newest version (1.4.20-1ubuntu3.3).
The following package was automatically installed and is no longer required:
  libuv1
Use 'sudo apt autoremove' to remove it.
0 to upgrade, 0 to newly install, 0 to remove and 193 not to upgrade.
sudo: unable to resolve host controlplane
Executing: /tmp/tmp.kovIcSooSL/gpg.1.sh --keyserver
keyserver.ubuntu.com
--recv-keys
3EFE0E0A2F2F60AA
gpg: requesting key 2F2F60AA from hkp server keyserver.ubuntu.com
```

**Comment by javajon** [comment]
@suyogpatil Thank you for alerting me to this! It has been fixed. The Tekton install has also been bumped to the latest version. Please give it a try again and let me know if you were successful, and most importantly if you learned something new.

Tekton and other topics around Kubernetes pipelines will be covered in my upcoming O'Reilly session in Part 2 of [Kubernetes in Three Weeks](https://learning.oreilly.com/live-training/courses/kubernetes-in-three-weeks/0636920385141/).

**Comment by suyogpatil** [comment]
thanks @javajon for quick fix ! Great stuff :)
